//
//  MoralDilemmaData.java
//  MoralIQ
//
//  Created by Simone Karani on 2/9/20.
//  Copyright © 2020 MoralIQ. All rights reserved.
//

package com.simonekarani.moraliq.dilemma;

import com.simonekarani.moraliq.R;

public class MoralDilemmaData {

    public static final String MDilemmaAnalysis1  = "Re-gifting is the process of getting a gift, and then giving that gift to someone else. It's generally frowned upon because it shows that you didn't really appreciate that gift and you don't care about the person who gave it to you.";
    public static final String MDilemmaAnalysis2  = "If you excuse yourself from this conversation, your colleague will probably find someone else to talk to. Most of us feel uncomfortable standing up for our time for fear that we will offend the other person. When you notice the telltale signs of another 20-minute conversation starting, you really can take a look at your watch and then excuse yourself by saying that there is a task you need to complete.";
    public static final String MDilemmaAnalysis3  = "Ghosting is often rude, or cruel thing to do, specially on a long term or serious relationship. It is usually recommended to call off in advance of the day. It may be better to be left from a person than leading an entire life with them";
    public static final String MDilemmaAnalysis4  = "Farmers who use GMO crops use fewer environmentally damaging pesticides, leading to feeding the world's growing population. The genetically modified foods should be safe to eat.";
    public static final String MDilemmaAnalysis5  = "Brother. Cancer vial can be reinvented by humans. Value of human life is bigger than the possible cure. Explain the consequences to son and father, and let them reason it out.";
    public static final String MDilemmaAnalysis6  = "Killing, a murder is a criminal offense punishable by law. Avoid Re-gifting is the process of getting a gift, and then giving that gift to someone else. It's generally frowned upon because it shows that you didn't really appreciate that gift and you don't care about the person who gave it to you.";
    public static final String MDilemmaAnalysis7  = "In order to avoid road rage, and avoid un-necessary traffic or accidents it is recommended to drive at the recommended state speed limit or the speed of the traffic.";
    public static final String MDilemmaAnalysis8  = "Trust is the currency in the 21st century. Earn trust today, and it will convert to future wealth. Live with average income today, and avoid quick get-rich illegal and dishonest ways.";
    public static final String MDilemmaAnalysis9  = "Trust is important in today's environment. You should accept discredit where discredit is due. Be honest, and explain the details to face the consequences together. In the long run, you will still have your friend and your boss will respect you for your truthfulness.";
    public static final String MDilemmaAnalysis10 = "For the accused innocent, it would take an entire lifetime to clear the guilt/stigma of a crime. You should convince/threaten your friend to confess their crime, or you may have to inform the police about the confession.";
    public static final String MDilemmaAnalysis11 = "We live in a society where we value our family, their lives and safety. Our family is precious, who stand for us in good/bad times. So saving parents who sacrificed, and helped you be who you are is important.";
    public static final String MDilemmaAnalysis12 = "Mob justice is not pracitised in our society and should not be used by Police or Sheriff. The society has built law and order to punish the crimes. Also, if a precedent is set in one example the mob may use it for all future violent crimes.";
    public static final String MDilemmaAnalysis13 = "Human actions are better controllable than untamed animals. Punching a baby is self-controlled, so one can create a playful punch without inflicting any pain.";
    public static final String MDilemmaAnalysis14 = "The meal is whatever - be it vegan, vegetarian or meat. Each meal should be balanced based on person's health and well-being.";
    public static final String MDilemmaAnalysis15 = "There have been lots of definitions of who is an alien or extraterrestrial life. A child after born is a life on earth. Ranson is a crime punishable by law, whether it is for money or human life.";
    public static final String MDilemmaAnalysis16 = "Fear may prevent some witnesses from reporting a crime. If fear or other emotional element is not the reason, then it should be reported. No amount of benevolence can erase the wrongness of a wrong act such as robbery. Robbery is a crime punishable by law.";
    public static final String MDilemmaAnalysis17 = "Friends provide a long term benefit - familiarity relationship. As time goes by in friendship both people learn each others likes and dislikes and those little buttons to push that make experience more pleasurable.";
    public static final String MDilemmaAnalysis18 = "Public opinion suggests that they support higher tax rate for rich people. Also, data from rich countries suggest fair to moderate tax rate for wealthy, and let wealthy do what they do best - Invest in domestic economy.";
    public static final String MDilemmaAnalysis19 = "No. The fairness cost might be measured in terms of \"Social inconvenience\" (opportunity costs of a year in jail for the wealthy man) or \"emotional pain\" (opportunity costs of public censure for the wealthy man). If cost is the fine, then fine must represent equal portion of wealth of both men.";
    public static final String MDilemmaAnalysis20 = "Yes. Good Citizenship responsibilities of a society. Also, there are circumstances in the event that the driver happens to have a means of noticing that you did not pay. Also, consider the reactions of the passengers who notice that I have not paid, and may point it out to the driver.";
    public static final String MDilemmaAnalysis21 = "$1000. One moral philosophy states that punishment on the theft should be on the basis of proportion of owner's wealth. At the same time $1000 can be extrapolated to $1 million to indicate a criminal mindset than the $100 which would indicate necessities.";
    public static final String MDilemmaAnalysis22 = "Group of five. One can base decision if other information were available - rescue children over adults, women over men, young over old, healthy over ill, more intelligent over less intelligent, ... In the case of missing information, rescue the greater number of people.";
    public static final String MDilemmaAnalysis23 = "Law prohibits stealing. He should try to do everything (loans, sell items, borrow from friends/family...) without breaking the law. If he gets caught, the oves ones would feel devastated and the entire family will be destroyed.";
    public static final String MDilemmaAnalysis24 = "Dog bites can happen for a lot of reasons from a puppy teething to an untrained dog. At the same time it is your friend's responsibility to make everyone aware of it. You should inform him, and have a \"No Tolerance rule\" of staying away from your friend's dog.";
    public static final String MDilemmaAnalysis25 = "The Trolley dilemma, and its variations have been widely studied. If we consider that everyone has equal rights, then we would be doing something wrong in sacrificing one even if our intention was to save five. Create alarm for five people, but in terms of action - do nothing.";
    public static final String MDilemmaAnalysis26 = "Do nothing. Terrorist cannot be trusted with their words. There may be a hidden agenda to capture your video and release it to media to proclaim you involved in terrorist organization.";
    public static final String MDilemmaAnalysis27 = "We can never understand the sheer depth of the grief, regret, and anger someone experiences at the loss of their loved ones. It is always important to comfort a grieving friend if you value your relationship with him.";
    public static final String MDilemmaAnalysis28 = "Bullying behavior should never be encouraged. Bullies are only as powerful as we allow them to be. Ask for help in dealing with bullies, but standup for yourself by being confident and speak with self-assurance.";
    public static final String MDilemmaAnalysis29 = "Pounds are local animal shelter places. If the random pound person approaches to take your pet, provide evidences to reclaim. If all fails, turn your pet in and find ways to reclaim.";
    public static final String MDilemmaAnalysis30 = "Trust is an important element of friendship, so no-no for friendship. There could be many reasons why girlfriend may be cheating - lost interest, cheating for a long time, cheating with multiple men, others. In some societies cheating in couples is accepted. If it bothers you, get all details by having discussion.";
    public static final String MDilemmaAnalysis31 = "The leader of the group is responsible for making the group's decisions. He is accountable for the success/failure of the group or any lives that are lost during the mission. It is best to take his advise before making the decision.";
    public static final String MDilemmaAnalysis32 = "Co-owners and stakeholders is the growth engine of today's wealth creation. Co-ownership is created by splitting bonuses based on performance, and contribution. It is a win-all thinking for long term growth.";
    public static final String MDilemmaAnalysis33 = "We live in a post war era, and US is a country where government keeps a list of eligible males that they can draft to serve in the military should there be a need. If civilians are drafted, it would mean a national emergency, and a national responsibility of every citizen.";
    public static final String MDilemmaAnalysis34 = "No. The thought of bringing a rapid victory, and killing civilians from bombs, and its radiation has been an immoral act. The act of bombs have devastated the minds of growing japanese civilians for decades.";
    public static final String MDilemmaAnalysis35 = "It is quite possible that this may not be the only reason for his promotion. Be creative by providing the details of the project, and your role and contribution to it. Request him to reassess the details of the project by asking team members.";

    public static final MoralDilemmaModel MDilemma1  =  new MoralDilemmaModel(20, 20, 30, 0, MDilemmaAnalysis1, "\n\nWould You Ever Re-Gift Something?", R.drawable.re_gift,  "No", "I would Re-Gift... To The Exact Same Person Who Gave It To Me...", "Maybe By Accident", "Yes");
    public static final MoralDilemmaModel MDilemma2  =  new MoralDilemmaModel(20, 18, 20, 0, MDilemmaAnalysis2, "\nYou're Stuck Talking To Someone Boring. How Do You Get Out Of The Situation?",R.drawable.talk_boring,  "Just Be Patient. Eventually You'll Have An Opportunity To Leave", "Tell Them To Their Face That They're Boring And You Don't Want To Talk To Them", "Invent Some Lame Excuse", "Just Keep Yawning Until They Get The Picture");
    public static final MoralDilemmaModel MDilemma3  =  new MoralDilemmaModel(19, 20, 30, 0, MDilemmaAnalysis3, "\nWould You Rather Be Left At The Altar Or Leave Your Fiancee At the Altar?", R.drawable.leave_altar,  "Be Left At the Altar", "Leave Your Fiancee At the Altar", "I Don't Plan On Getting Married", "I'd Rather Be Priest, Then I'd Get To Laugh At This Situation");
    public static final MoralDilemmaModel MDilemma4  =  new MoralDilemmaModel(19, 19, 30, 3, MDilemmaAnalysis4, "\nIs It Ok To Genetically Modify Food In Order To Feed More People?", R.drawable.gmo_food,  "No", "Yes", "No, But It's Ok To Genetically Modify Food To Make Money", "Only If Extensive Reearch Is Done To Determine The Health Risks");
    public static final MoralDilemmaModel MDilemma5  =  new MoralDilemmaModel(18, 20, 30, 0, MDilemmaAnalysis5, "Your Brother Fell Into Quicksand. 7 feet Away Is a Vial Containing The Only Known Cure For Cancer. You Only Have Time To Save One. Which Do you Save?", R.drawable.brother_sand,  "Your Brother", "The Vial", "Ask Your Brother What He Wants You To Do?", "Neither");
    public static final MoralDilemmaModel MDilemma6  =  new MoralDilemmaModel(18, 19, 30, 3, MDilemmaAnalysis6, "A Man Tells You His Terminally Ill Father's Insurance Policy Will Expire At Midnight. If He Dies After Midnight, He Gets No Money. He Asks You To Kill His Father With A Pillow. Do You...", R.drawable.insurance_death,  "Do Nothing", "Ask For Half The Money, Then Kill The Father", "Kill The Father", "Tell The Father About The Plan, Then Watch The Ensuing Argument");
    public static final MoralDilemmaModel MDilemma7  =  new MoralDilemmaModel(20, 20, 50, 1, MDilemmaAnalysis7, "\n\nWhat's The Correct Speed To Drive At?", R.drawable.drive_speed,  "Always Under The Speed Limit", "The Speed Of Traffic", "Over The Speed Limit", "Whatever Gets Me There Fastest");
    public static final MoralDilemmaModel MDilemma8  =  new MoralDilemmaModel(20, 20, 50, 2, MDilemmaAnalysis8, "Would You Rather Be Forever Poor And Honest, Or Get Rich By Doing Illegal Things?", R.drawable.p_rich,  "Be Poor And Honest", "Get Rich By Doing Illegal Things", "I'd Rather Just Have An Average Income And Be Slightly Trustworthy", "I'd Rather Be Poor And Dishonest");
    public static final MoralDilemmaModel MDilemma9  =  new MoralDilemmaModel(16, 20, 30, 3, MDilemmaAnalysis9, "Your Boss Calls You In. A Mistake Has Been Made. It's Partly Your Fault And Your Best Friend's. The Boss Has Decided To Fire One Person. Do You Take Responsibility, Or Do You PERSONALLY Fire Your Best Friend?", R.drawable.boss_mistake,  "Fire My Best Friend", "Take Responsibility And Get Fired", "Try And Blame It On The Janitor", "Tell Him The Truth That You Were Both Responsible");
    public static final MoralDilemmaModel MDilemma10  = new MoralDilemmaModel(19, 18, 20, 0, MDilemmaAnalysis10, "A Friend Confesses That They Committed A Crime. But They Make You Promise Not To Tell. An Innocent Person Is Accused Of The Crime. What Do You Do?", R.drawable.accuse_crime,  "Inform The Police That Your Friend Is The Guilty One", "Keep Quiet", "Testify In Court That You Saw The Innocent Person Committing The Crime", "Ask Your Friend To Give You Money In Exchange For Keeping Quiet");
    public static final MoralDilemmaModel MDilemma11  = new MoralDilemmaModel(20, 20, 40, 0, MDilemmaAnalysis11, "\nWould You Rather Save A Random Baby Or Save Your Parents?", R.drawable.save_baby,  "My Parents", "The Random Baby", "Neither", "My Parents Have Already Passed Away");
    public static final MoralDilemmaModel MDilemma12  = new MoralDilemmaModel(18, 20, 30, 1, MDilemmaAnalysis12, "You're A Sheriff In The Wild West. An Angry Mob Wants You To Hand Over A Suspect Of A Violent Crime To Them. If You Don't, The Mob Will Destroy Property And Injure Innocent Civilians. Do You...", R.drawable.crime_mob,  "Hand Over The Suspect", "Keep The Suspect In Custody", "Arrest Everyone", "Give The Mob A Person Dressed Up Like The Suspect");
    public static final MoralDilemmaModel MDilemma13  = new MoralDilemmaModel(20, 20, 50, 1, MDilemmaAnalysis13, "\nWould You Rather Get Punched By A Gorilla, Or Punch A Small Child?", R.drawable.punch_gorilla,  "Get Punched By A Gorilla", "Punch The Small Child", "Both", "Run Away");
    public static final MoralDilemmaModel MDilemma14  = new MoralDilemmaModel(20, 20, 50, 1, MDilemmaAnalysis14, "\n\nWhat Is Your Diet?", R.drawable.p_diet,  "Mostly Meat", "Whatever I Want", "Vegetarian", "Vegan");
    public static final MoralDilemmaModel MDilemma15  = new MoralDilemmaModel(19, 20, 20, 1, MDilemmaAnalysis15, "A Powerful Alien Visits Earth, With The Promise To Eradicate War, Disease, And All Suffering. In Return, He Demands A Small Child. What Do You Do?", R.drawable.alien_war,  "Give The Child To The Alien", "Do Nothing", "Give Him Seven Children, And Ask Him To Make You King", "Capture The Alien, And Sell Him To The CIA For Cash");
    public static final MoralDilemmaModel MDilemma16  = new MoralDilemmaModel(19, 20, 20, 0, MDilemmaAnalysis16, "You Witness A Bank Robbery. The Man Runs Outside And Donates The Money To An Orphanage. If You Report Him, The Money Will Be Returned. What Do You Do?", R.drawable.bank_robbery,  "Report Him", "Do Nothing", "Ask For The Money In Return For Not Reporting Him", "Threaten To Report Him Unless He Donates To The Charity of Your Choice");
    public static final MoralDilemmaModel MDilemma17  = new MoralDilemmaModel(20, 20, 40, 2, MDilemmaAnalysis17, "\nWould You Rather Have A Friend With Benefits Or A One Night Stand?", R.drawable.friend_night,  "Both, At The Same Time", "One Night Stand", "Friends With Benefits", "Neither. I'd Prefer A Lasting Relationship");
    public static final MoralDilemmaModel MDilemma18  = new MoralDilemmaModel(20, 20, 40, 0, MDilemmaAnalysis18, "\nShould The Wealthier Members Of Society Be Taxed To Pay For The Poorer Members?", R.drawable.wealthy_tax,  "At Least 25%", "Everyone Should Be Taxed The Same", "They Shouldn't Be Taxed", "No One Should Pay Any Taxes");
    public static final MoralDilemmaModel MDilemma19  = new MoralDilemmaModel(18, 17, 10, 2, MDilemmaAnalysis19, "A Rich Man And A Poor Man Commit The Exact Same Crime. The Poor Man Goes To Jail For One Year, While The Rich Man Pays A $10,000 Fine. How Would You Change This?", R.drawable.crime_rich,  "I Would Eliminate The Option To Pay A Fine - Jail Time For Everyone", "I Wouldn't Change The System - It's Perfectly Fine The Way It Is", "I Would Make The Fine Proportional To Income Of The Criminal", "There Should Be An Option To Fight The Judge In An Arena For The Right To Walk Free");
    public static final MoralDilemmaModel MDilemma20  = new MoralDilemmaModel(20, 20, 40, 0, MDilemmaAnalysis20, "You Get On The Bus But The Driver Steps Out To Get Coffee Before You Can Pay. Do You Still Pay The Fare?", R.drawable.pay_driver,  "I Would Still Pay", "I Wouldn't Pay", "Drive The Bus Away", "I Wouldn't Pay And I'd Report Him");
    public static final MoralDilemmaModel MDilemma21  = new MoralDilemmaModel(20, 20, 30, 0, MDilemmaAnalysis21, "If You Were In Charge Of The Government, Which Crime Would Carry The Bigger Punishment, The Theft Of $1000 Or $100?", R.drawable.charge_crime,  "$1000", "Both Would Carry The Death Penalty", "Both Would Carry The Same Amount Of Jail Time", "$100");
    public static final MoralDilemmaModel MDilemma22  = new MoralDilemmaModel(19, 20, 40, 0, MDilemmaAnalysis22, "You Are On A Boat And See Two Rocks With People Stranded On Them - 4 On One, 5 On The Other. You Can Only Save One Group. Which Do You Choose?", R.drawable.group_save,  "The Group of 5", "The Group of Four", "Neither Group, But You Go And Find Help", "Juist Sail By Laughing");
    public static final MoralDilemmaModel MDilemma23  = new MoralDilemmaModel(19, 20, 30, 1, MDilemmaAnalysis23, "The Only Cure To Save Your Loved One Is Too Expensive For You To Buy. You Think You Can Get Away With Stealing It. Do You Try?", R.drawable.cure_steal,  "Yes", "No", "Yes, And I Would Kill Anyone Who Stood In My Way", "I Would Try To Create My Own Cure");
    public static final MoralDilemmaModel MDilemma24  = new MoralDilemmaModel(20, 20, 20, 3, MDilemmaAnalysis24, "You Are Bitten By Your Friend's Dog. It's Obviously Not Well Trained. What Do You Do?", R.drawable.dog_bitten,  "Nothing", "Call The Authorities And Make Sure The Dog Is Put Down", "Kick The Dog", "Tell Your Friend That You're Concerned About The Dog Not Being Trained");
    public static final MoralDilemmaModel MDilemma25  = new MoralDilemmaModel(20, 20, 20, 2, MDilemmaAnalysis25, "A Runaway Trolley Is Headed Towards Five Workers. It Will Kill Them. You Can Save Five By Sacrificing One. What Do You Do?", R.drawable.run_trolley,  "Push The Fat Man Onto The Tracks", "Video Tape The Incident And Post It Online", "Do Nothing", "Watch The Incident, Then Claim Worker's Compensation For The Emotional Trauma Of Witnessing It");
    public static final MoralDilemmaModel MDilemma26  = new MoralDilemmaModel(18, 18, 10, 1, MDilemmaAnalysis26, "You And 8 Others Are Captured By Terrorists. The Leader Says He Will Free Everyone You If You Help Torture Another Hostage. If You Refuse, They Will Kill All Of You. What Do You Do?", R.drawable.terrorist_torture,  "Help Torture The Person", "Do Nothing", "Help Torture The Person. Then Torture The Rest Of The Hostages. Then Join The Terrorist Group", "Agree To Partake In The Torture. Wait Till They Free You From Your Restraints, Then Run Away, Leaving The Others To Die");
    public static final MoralDilemmaModel MDilemma27  = new MoralDilemmaModel(19, 20, 20, 0, MDilemmaAnalysis27, "You've Just Been Complaining To A Friend About How Annoying Your Parents Are. Then You Find Out Their Parents Just Died. How Do You Proceed?", R.drawable.annoy_parents,  "Say\"I'm So Sorry That Was Extremely Insensitive Of Me\"", "Laugh At Them", "Just The Awkward Silence Happen", "Say \"How Was I Supposed To Know?\"");
    public static final MoralDilemmaModel MDilemma28  = new MoralDilemmaModel(20, 20, 40, 3, MDilemmaAnalysis28, "\n\nWhat's The Best Way To Deal With A Bully?", R.drawable.kids_bully,  "Kill 'Em With Kindness", "Kill Them", "Ignore Them", "Stand Up For Yourself");
    public static final MoralDilemmaModel MDilemma29  = new MoralDilemmaModel(20, 20, 40, 1, MDilemmaAnalysis29, "Would You Rather Give Your Pet To The Pound, Or Press A Button That Killed A Random Stranger?", R.drawable.pet_kill,  "Press The Button", "Turn Your Pet In", "Kill Both Pet And Stranger", "Run Away");
    public static final MoralDilemmaModel MDilemma30  = new MoralDilemmaModel(20, 20, 40, 3, MDilemmaAnalysis30, "Would You Rather Catch Your Best Friend Cheating, Or Have Your Best Friend Catch YOU Cheating?", R.drawable.boss_cheat,  "Have My Best Friend Catch Me Cheating", "Catch My Best Friend Cheating", "Cheat On My Partner With Their Best Friend", "Catch My Girlfriend Cheating On Me");
    public static final MoralDilemmaModel MDilemma31  = new MoralDilemmaModel(18, 20, 30, 0, MDilemmaAnalysis31, "A Man Is Leading A Group Out Of A Cave. He Becomes Stuck. In A Few Hours, The Cave Will Be Flooded By Water, Killing The Group. Do You Use Dynamite To Blow Him Up?", R.drawable.cave_blow,  "Use The Dynamite, But Only If He Agrees", "Use The Dynamite Immediately", "Do Nothing", "Video Tape Him Being Stuck, Then Use The Dynamite");
    public static final MoralDilemmaModel MDilemma32  = new MoralDilemmaModel(20, 20, 40, 1, MDilemmaAnalysis32, "Would You Rather Take A $10,000 Bonus For Yourself, Or Split It With Your Co-Workers?", R.drawable.bonus_work,  "Take The Bonus For Myself", "Split It With Co-Workers", "Neither", "Ask For More Money");
    public static final MoralDilemmaModel MDilemma33  = new MoralDilemmaModel(18, 20, 30, 0, MDilemmaAnalysis33, "You Have Been Drafted Into The Military. After Your Physical, They Make A Mistake, Wrongly Diagnosing You With An Illness That Would Exclude You From Service. What Do You Do?", R.drawable.military_ill,  "Inform Them They Made A Mistake", "Do Nothing", "Sue For Discrimination", "Laugh At The People Who Have To Go To War");
    public static final MoralDilemmaModel MDilemma34  = new MoralDilemmaModel(19, 17, 7,  1, MDilemmaAnalysis34,  "It's The End Of WW2. Dropping The Atom Bomb On Japan Would Save The Lives Of Countless American By Making Japan Surrender. Would You Do It?", R.drawable.ww2_bomb,  "Yes", "No", "I Would Drop A Nuke On Every Japanese City, Comppublic static final MoralDilemmaModelely Destroying The Entire Country", "I Would Give Japan Nukes, And Then Explain The Intricacies Of Mutually Assured Destruction");
    public static final MoralDilemmaModel MDilemma35  = new MoralDilemmaModel(20, 18, 30, 1, MDilemmaAnalysis35, "Your Boss Calls You In Again. He Wants You To Promote Jeremy For Work That You Actually Did. What Do You Do?", R.drawable.boss_promotion,  "Say Nothing", "Point Out That You Actually Did That Work", "Accept That You Learned A Lot From Your Hard Work Even Without The Promotion", "Sabotage Jeremy In The Future");

    public static final MoralDilemmaModel MoralDilemmaDataList[];

    static {
        MoralDilemmaDataList = new MoralDilemmaModel[]{
                MDilemma1, MDilemma2, MDilemma3, MDilemma4, MDilemma5,
                MDilemma6, MDilemma7, MDilemma8, MDilemma9, MDilemma10,
                MDilemma11, MDilemma12, MDilemma13, MDilemma14, MDilemma15,
                MDilemma16, MDilemma17, MDilemma18, MDilemma19, MDilemma20,
                MDilemma21, MDilemma22, MDilemma23, MDilemma24, MDilemma25,
                MDilemma26, MDilemma27, MDilemma28, MDilemma29, MDilemma30,
                MDilemma31, MDilemma32, MDilemma33, MDilemma34, MDilemma35
        };
    }
}
