//
//  MoralDilemmaData.java
//  MoralIQ
//
//  Created by Simone Karani on 2/9/20.
//  Copyright © 2020 MoralIQ. All rights reserved.
//

package com.simonekarani.moraliq.dilemma;

import com.simonekarani.moraliq.R;

public class MoralDilemmaData {

    public static final MoralDilemmaModel MDilemma1  =  new MoralDilemmaModel(20, 20, 30,"\n\nWould You Ever Re-Gift Something?", R.drawable.re_gift,  "No", "I would Re-Gift... To The Exact Same Person Who Gave It To Me...", "Maybe By Accident", "Yes");
    public static final MoralDilemmaModel MDilemma2  =  new MoralDilemmaModel(20, 18, 20,"\nYou're Stuck Talking To Someone Boring. How Do You Get Out Of The Situation?",R.drawable.talk_boring,  "Just Be Patient. Eventually You'll Have An Opportunity To Leave", "Tell Them To Their Face That They're Boring And You Don't Want To Talk To Them", "Invent Some Lame Excuse", "Just Keep Yawning Until They Get The Picture");
    public static final MoralDilemmaModel MDilemma3  =  new MoralDilemmaModel(19, 20, 30,"\nWould You Rather Be Left At The Altar Or Leave Your Fiancee At the Altar?", R.drawable.leave_altar,  "Be Left At the Altar", "Leave Your Fiancee At the Altar", "I Don't Plan On Getting Married", "I'd Rather Be Priest, Then I'd Get To Laugh At This Situation");
    public static final MoralDilemmaModel MDilemma4  =  new MoralDilemmaModel(19, 19, 30,"\nIs It Ok To Genetically Modify Food In Order To Feed More People?", R.drawable.gmo_food,  "No", "Yes", "No, But It's Ok To Genetically Modify Food To Make Money", "Only If Extensive Reearch Is Done To Determine The Health Risks");
    public static final MoralDilemmaModel MDilemma5  =  new MoralDilemmaModel(18, 20, 30,"Your Brother Fell Into Quicksand. 7 feet Away Is a Vial Containing The Only Known Cure For Cancer. You Only Have Time To Save One. Which Do you Save?", R.drawable.brother_sand,  "Your Brother", "The Vial", "Ask Your Brother What He Wants You To Do?", "Neither");
    public static final MoralDilemmaModel MDilemma6  =  new MoralDilemmaModel(18, 19, 30,"A Man Tells You His Terminally Ill Father's Insurance Policy Will Expire At Midnight. If He Dies After Midnight, He Gets No Money. He Asks You To Kill His Father With A Pillow. Do You...", R.drawable.insurance_death,  "Do Nothing", "Ask For Half The Money, Then Kill The Father", "Kill The Father", "Tell The Father About The Plan, Then Watch The Ensuing Argument");
    public static final MoralDilemmaModel MDilemma7  =  new MoralDilemmaModel(20, 20, 50,"\n\nWhat's The Correct Speed To Drive At?", R.drawable.drive_speed,  "Always Under The Speed Limit", "The Speed Of Traffic", "Over The Speed Limit", "Whatever Gets Me There Fastest");
    public static final MoralDilemmaModel MDilemma8  =  new MoralDilemmaModel(20, 20, 50,"Would You Rather Be Forever Poor And Honest, Or Get Rich By Doing Illegal Things?", R.drawable.p_rich,  "Be Poor And Honest", "Get Rich By Doing Illegal Things", "I'd Rather Just Have An Average Income And Be Slightly Trustworthy", "I'd Rather Be Poor And Dishonest");
    public static final MoralDilemmaModel MDilemma9  =  new MoralDilemmaModel(16, 20, 30,"Your Boss Calls You In. A Mistake Has Been Made. It's Partly Your Fault And Your Best Friend's. The Boss Has Decided To Fire One Person. Do You Take Responsibility, Or Do You PERSONALLY Fire Your Best Friend?", R.drawable.boss_mistake,  "Fire My Best Friend", "Take Responsibility And Get Fired", "Try And Blame It On The Janitor", "Tell Him The Truth That You Were Both Responsible");
    public static final MoralDilemmaModel MDilemma10  = new MoralDilemmaModel(19, 18, 20, "A Friend Confesses That They Committed A Crime. But They Make You Promise Not To Tell. An Innocent Person Is Accused Of The Crime. What Do You Do?", R.drawable.accuse_crime,  "Inform The Police That Your Friend Is The Guilty One", "Keep Quiet", "Testify In Court That You Saw The Innocent Person Committing The Crime", "Ask Your Friend To Give You Money In Exchange For Keeping Quiet");
    public static final MoralDilemmaModel MDilemma11  = new MoralDilemmaModel(20, 20, 40, "\nWould You Rather Save A Random Baby Or Save Your Parents?", R.drawable.save_baby,  "My Parents", "The Random Baby", "Neither", "My Parents Have Already Passed Away");
    public static final MoralDilemmaModel MDilemma12  = new MoralDilemmaModel(18, 20, 30, "You're A Sheriff In The Wild West. An Angry Mob Wants You To Hand Over A Suspect Of A Violent Crime To Them. If You Don't, The Mob Will Destroy Property And Injure Innocent Civilians. Do You...", R.drawable.crime_mob,  "Hand Over The Suspect", "Keep The Suspect In Custody", "Arrest Everyone", "Give The Mob A Person Dressed Up Like The Suspect");
    public static final MoralDilemmaModel MDilemma13  = new MoralDilemmaModel(20, 20, 50, "\nWould You Rather Get Punched By A Gorilla, Or Punch A Small Child?", R.drawable.punch_gorilla,  "Get Punched By A Gorilla", "Punch The Small Child", "Both", "Run Away");
    public static final MoralDilemmaModel MDilemma14  = new MoralDilemmaModel(20, 20, 50, "\n\nWhat Is Your Diet?", R.drawable.p_diet,  "Mostly Meat", "Whatever I Want", "Vegetarian", "Vegan");
    public static final MoralDilemmaModel MDilemma15  = new MoralDilemmaModel(19, 20, 20, "A Powerful Alien Visits Earth, With The Promise To Eradicate War, Disease, And All Suffering. In Return, He Demands A Small Child. What Do You Do?", R.drawable.alien_war,  "Give The Child To The Alien", "Do Nothing", "Give Him Seven Children, And Ask Him To Make You King", "Capture The Alien, And Sell Him To The CIA For Cash");
    public static final MoralDilemmaModel MDilemma16  = new MoralDilemmaModel(19, 20, 20, "You Witness A Bank Robbery. The Man Runs Outside And Donates The Money To An Orphanage. If You Report Him, The Money Will Be Returned. What Do You Do?", R.drawable.bank_robbery,  "Report Him", "Do Nothing", "Ask For The Money In Return For Not Reporting Him", "Threaten To Report Him Unless He Donates To The Charity of Your Choice");
    public static final MoralDilemmaModel MDilemma17  = new MoralDilemmaModel(20, 20, 40, "\nWould You Rather Have A Friend With Benefits Or A One Night Stand?", R.drawable.friend_night,  "Both, At The Same Time", "One Night Stand", "Friends With Benefits", "Neither. I'd Prefer A Lasting Relationship");
    public static final MoralDilemmaModel MDilemma18  = new MoralDilemmaModel(20, 20, 40, "\nShould The Wealthier Members Of Society Be Taxed To Pay For The Poorer Members?", R.drawable.wealthy_tax,  "At Least 25%", "Everyone Should Be Taxed The Same", "They Shouldn't Be Taxed", "No One Should Pay Any Taxes");
    public static final MoralDilemmaModel MDilemma19  = new MoralDilemmaModel(18, 17, 10, "A Rich Man And A Poor Man Commit The Exact Same Crime. The Poor Man Goes To Jail For One Year, While The Rich Man Pays A $10,000 Fine. How Would You Change This?", R.drawable.crime_rich,  "I Would Eliminate The Option To Pay A Fine - Jail Time For Everyone", "I Wouldn't Change The System - It's Perfectly Fine The Way It Is", "I Would Make The Fine Proportional To Income Of The Criminal", "There Should Be An Option To Fight The Judge In An Arena For The Right To Walk Free");
    public static final MoralDilemmaModel MDilemma20  = new MoralDilemmaModel(20, 20, 40, "You Get On The Bus But The Driver Steps Out To Get Coffee Before You Can Pay. Do You Still Pay The Fare?", R.drawable.pay_driver,  "I Would Still Pay", "I Wouldn't Pay", "Drive The Bus Away", "I Wouldn't Pay And I'd Report Him");
    public static final MoralDilemmaModel MDilemma21  = new MoralDilemmaModel(20, 20, 30, "If You Were In Charge Of The Government, Which Crime Would Carry The Bigger Punishment, The Theft Of $1000 Or $100?", R.drawable.charge_crime,  "$1000", "Both Would Carry The Death Penalty", "Both Would Carry The Same Amount Of Jail Time", "$100");
    public static final MoralDilemmaModel MDilemma22  = new MoralDilemmaModel(19, 20, 40, "You Are On A Boat And See Two Rocks With People Stranded On Them - 4 On One, 5 On The Other. You Can Only Save One Group. Which Do You Choose?", R.drawable.group_save,  "The Group of 5", "The Group of Four", "Neither Group, But You Go And Find Help", "Juist Sail By Laughing");
    public static final MoralDilemmaModel MDilemma23  = new MoralDilemmaModel(19, 20, 30, "The Only Cure To Save Your Loved One Is Too Expensive For You To Buy. You Think You Can Get Away With Stealing It. Do You Try?", R.drawable.cure_steal,  "Yes", "No", "Yes, And I Would Kill Anyone Who Stood In My Way", "I Would Try To Create My Own Cure");
    public static final MoralDilemmaModel MDilemma24  = new MoralDilemmaModel(20, 20, 20, "You Are Bitten By Your Friend's Dog. It's Obviously Not Well Trained. What Do You Do?", R.drawable.dog_bitten,  "Nothing", "Call The Authorities And Make Sure The Dog Is Put Down", "Kick The Dog", "Tell Your Friend That You're Concerned About The Dog Not Being Trained");
    public static final MoralDilemmaModel MDilemma25  = new MoralDilemmaModel(20, 20, 20, "A Runaway Trolley Is Headed Towards Five Workers. It Will Kill Them. You Can Save Five By Sacrificing One. What Do You Do?", R.drawable.run_trolley,  "Push The Fat Man Onto The Tracks", "Video Tape The Incident And Post It Online", "Do Nothing", "Watch The Incident, Then Claim Worker's Compensation For The Emotional Trauma Of Witnessing It");
    public static final MoralDilemmaModel MDilemma26  = new MoralDilemmaModel(18, 18, 10, "You And 8 Others Are Captured By Terrorists. The Leader Says He Will Free Everyone You If You Help Torture Another Hostage. If You Refuse, They Will Kill All Of You. What Do You Do?", R.drawable.terrorist_torture,  "Help Torture The Person", "Do Nothing", "Help Torture The Person. Then Torture The Rest Of The Hostages. Then Join The Terrorist Group", "Agree To Partake In The Torture. Wait Till They Free You From Your Restraints, Then Run Away, Leaving The Others To Die");
    public static final MoralDilemmaModel MDilemma27  = new MoralDilemmaModel(19, 20, 20, "You've Just Been Complaining To A Friend About How Annoying Your Parents Are. Then You Find Out Their Parents Just Died. How Do You Proceed?", R.drawable.annoy_parents,  "Say\"I'm So Sorry That Was Extremely Insensitive Of Me\"", "Laugh At Them", "Just public static final MoralDilemmaModel The Awkward Silence Happen", "Say \"How Was I Supposed To Know?\"");
    public static final MoralDilemmaModel MDilemma28  = new MoralDilemmaModel(20, 20, 40, "\n\nWhat's The Best Way To Deal With A Bully?", R.drawable.kids_bully,  "Kill 'Em With Kindness", "Kill Them", "Ignore Them", "Stand Up For Yourself");
    public static final MoralDilemmaModel MDilemma29  = new MoralDilemmaModel(20, 20, 40, "Would You Rather Give Your Pet To The Pound, Or Press A Button That Killed A Random Stranger?", R.drawable.pet_kill,  "Press The Button", "Turn Your Pet In", "Kill Both Pet And Stranger", "Run Away");
    public static final MoralDilemmaModel MDilemma30  = new MoralDilemmaModel(20, 20, 40, "Would You Rather Catch Your Best Friend Cheating, Or Have Your Best Friend Catch YOU Cheating?", R.drawable.boss_cheat,  "Have My Best Friend Catch Me Cheating", "Catch My Best Friend Cheating", "Cheat On My Partner With Their Best Friend", "Catch My Girlfriend Cheating On Me");
    public static final MoralDilemmaModel MDilemma31  = new MoralDilemmaModel(18, 20, 30, "A Man Is Leading A Group Out Of A Cave. He Becomes Stuck. In A Few Hours, The Cave Will Be Flooded By Water, Killing The Group. Do You Use Dynamite To Blow Him Up?", R.drawable.cave_blow,  "Use The Dynamite, But Only If He Agrees", "Use The Dynamite Immediately", "Do Nothing", "Video Tape Him Being Stuck, Then Use The Dynamite");
    public static final MoralDilemmaModel MDilemma32  = new MoralDilemmaModel(20, 20, 40, "Would You Rather Take A $10,000 Bonus For Yourself, Or Split It With Your Co-Workers?", R.drawable.bonus_work,  "Take The Bonus For Myself", "Split It With Co-Workers", "Neither", "Ask For More Money");
    public static final MoralDilemmaModel MDilemma33  = new MoralDilemmaModel(18, 20, 30, "You Have Been Drafted Into The Military. After Your Physical, They Make A Mistake, Wrongly Diagnosing You With An Illness That Would Exclude You From Service. What Do You Do?", R.drawable.military_ill,  "Inform Them They Made A Mistake", "Do Nothing", "Sue For Discrimination", "Laugh At The People Who Have To Go To War");
    public static final MoralDilemmaModel MDilemma34  = new MoralDilemmaModel(19, 17, 7,  "It's The End Of WW2. Dropping The Atom Bomb On Japan Would Save The Lives Of Countless American By Making Japan Surrender. Would You Do It?", R.drawable.ww2_bomb,  "Yes", "No", "I Would Drop A Nuke On Every Japanese City, Comppublic static final MoralDilemmaModelely Destroying The Entire Country", "I Would Give Japan Nukes, And Then Explain The Intricacies Of Mutually Assured Destruction");
    public static final MoralDilemmaModel MDilemma35  = new MoralDilemmaModel(20, 18, 30, "Your Boss Calls You In Again. He Wants You To Promote Jeremy For Work That You Actually Did. What Do You Do?", R.drawable.boss_promotion,  "Say Nothing", "Point Out That You Actually Did That Work", "Accept That You Learned A Lot From Your Hard Work Even Without The Promotion", "Sabotage Jeremy In The Future");

    public static final MoralDilemmaModel MoralDilemmaDataList[];

    static {
        MoralDilemmaDataList = new MoralDilemmaModel[]{
                MDilemma1, MDilemma2, MDilemma3, MDilemma4, MDilemma5,
                MDilemma6, MDilemma7, MDilemma8, MDilemma9, MDilemma10,
                MDilemma11, MDilemma12, MDilemma13, MDilemma14, MDilemma15,
                MDilemma16, MDilemma17, MDilemma18, MDilemma19, MDilemma20,
                MDilemma21, MDilemma22, MDilemma23, MDilemma24, MDilemma25,
                MDilemma26, MDilemma27, MDilemma28, MDilemma29, MDilemma30,
                MDilemma31, MDilemma32, MDilemma33, MDilemma34, MDilemma35
        };
    }
}
