//  TechEthicsData.java
//  MoralIQ
//
//  Created by Simone Karani on 2/9/20.
//  Copyright © 2020 MoralIQ. All rights reserved.
//

package com.simonekarani.moraliq.techethics;

import com.simonekarani.moraliq.R;

public class TechEthicsData {
    public static final String TechEthicsAnalysis1   = "No, Human Society has progressed because of qualms of humans - diversity, disabilities and others. Special kids have used their determination beyond the norm of other kids to grow, evolve and succeed in this world.";
    public static final String TechEthicsAnalysis2   = "No, 21st century is seeing a surge in cyber-terrorism, deep fakes, and other technologies demands a need for personal protection and society abuse. Congress stated customers not visit or sign-up for service if personal privacy policy does not exist.";
    public static final String TechEthicsAnalysis3   = "No, Autonomous machines or Robots from a moral perspective cannot take responsibility for their actions. Robots programmability can be maipulated by bad actors.";
    public static final String TechEthicsAnalysis4   = "Yes, Biological agents like nuclear bomb has the potential to cause massive loss of human lives and panic across any country.";
    public static final String TechEthicsAnalysis5   = "Yes, as far as the gene editing is not performed in human embryos. Genome editing, once proved safe and effective, should be allowed to cure genetic disease for personalized treatment";
    public static final String TechEthicsAnalysis6   = "No, Implanting chips in humans has privacy and security implications that go beyond cameras in public places, facial recognition, tracking our locations, our driving habits, our spending histories, and even beyond ownership of our data.";
    public static final String TechEthicsAnalysis7   = "No, both the studies of modifying human embryos for in vitro studies and in vivo studies cross boundaries of human society - mixture between species may create problem in determination of the species.";
    public static final String TechEthicsAnalysis8   = "No, deepfakes / photoshopping has existed in movies and other applications. We should build technologies to detect deepfakes from genuine content.";
    public static final String TechEthicsAnalysis9   = "Yes, development of technology for protecting vast farm lands is important. In the future, the same technology can have many good applications. It is the same DARPA who brought the technology behind Internet, GPS, and others.";
    public static final String TechEthicsAnalysis10  = "No, sensitive data should be shared with the person's consent. The value of Fitbits fitness tracker direct-to-doctor data transmission helps in the care of the patient.";
    public static final String TechEthicsAnalysis11  = "Yes, Drug companies hire private physicians to plan, run, design and analyze clinical trials. Data obtained from the trials ensure the safety and effectiveness of drugs before they make it into the hands of patients.";
    public static final String TechEthicsAnalysis12  = "No, Social credit system creates a personality based on the rules of the credit system. Innovation, and creativity the pillars of growth in human society are not born by the limitations imposed by the system.";
    public static final String TechEthicsAnalysis13  = "No, software is always biased and is based on criterias like race, social system, credit history, and others. Humans as jurors or judges bring in elements of not having preconceived opinions on suspects.";
    public static final String TechEthicsAnalysis14  = "Yes, some states in US have created fines for distracted drivers. Cell phone messages provide similar information as CCTV street cameras. The cell phone checks should not compromise human privacy, and should be limited to time logs, and not the personal content.";
    public static final String TechEthicsAnalysis15  = "No, human emotions and buying patterns can be abused. Media has directed ads to arouse emotions on human buying patterns. Personalized patterns can be created to arouse human behaviors, and is a violation of Personal privacy.";
    public static final String TechEthicsAnalysis16  = "No, as it just does not encourage other criminals to get involved in this type of illegal activity. Also, there is no guarantee organization will get its data back. Govt. should create cyber-police to help civilians against criminals in digital era.";
    public static final String TechEthicsAnalysis17  = "No, it will open a backdoor or bypass for cyber-criminals. Law and enforcement agencies need to create a parallel system for surveillance on criminal activity and accessing data on phones. Apple may lose trust from its customer base in terms of personal privacy.";
    public static final String TechEthicsAnalysis18  = "Yes, Streaming live events should be limited only to security or other law-order agencies. If broadcasted to all, it can be abused for wrong reasons, and can jeopardise the actions taken against the criminal act.";
    public static final String TechEthicsAnalysis19  = "No, AI enabled bots or Woebots can act as compliments for positive psychology and assist medical specialists to understand individual psychology. Human mindset is unpredictable, and machine learning cannot be easily applied. Even 1% failure rate in mental health diagnosis is considered disastrous.";
    public static final String TechEthicsAnalysis20  = "Yes, In the digital era every system is getting AI powered where the morals, fairness and bias are software algorithms. Some form of oath of morality is needed for Software designers / programmers to enforce guardrails in the software.";
    public static final String TechEthicsAnalysis21  = "Yes, election polling the messages directly influenced political self-expression, information seeking and real-world voting behaviour of millions of peopleRe-gifting is the process of getting a gift, and then giving that gift to someone else. It's generally frowned upon because it shows that you didn't really appreciate that gift and you don't care about the person who gave it to you.";
    public static final String TechEthicsAnalysis22  = "No, Financial markets work on many factors - business model, future revenues, vision, CEO vision, political env, and many other factors which are unpredictable. Robo-advisor can’t provide guidance during market panic, but can act as substitute for low-cost investors.";
    public static final String TechEthicsAnalysis23  = "Yes, Facebook is a social media platform and it should provide its users the option to disable data collection or sharing. Also, facebook should adhere to data protection regulations as required by specific countries.";
    public static final String TechEthicsAnalysis24  = "Yes, Digital era is influenced by AI systems to promote innovation and growth. We need to re-skill and train the workforce to address global challenges, and boost jobs.";
    public static final String TechEthicsAnalysis25  = "No, We are in a phase of Robot / AI evolution - automation, self-learning to building moral based Ethical AI. The rogue in AI are the malfunctioning algorithms that need to be corrected by regulatory laws.";
    public static final String TechEthicsAnalysis26  = "No, Robots are not humans. Society with citizenship status was built by human-species. Future robots with AI powered, moral values and sense of multiplicity can be classified as robot-species may have to create their own form of identification, not necessarily citizenship.";

    public static final TechEthicsModel TEthics1  =  new TechEthicsModel("Should we edit our children's genes?",22, R.drawable.techthics_1,20, 15, 1, TechEthicsAnalysis1, "Yes", "No", "Maybe, to eliminate genetic related diseases", "Yes, to support generation of tissues and whole organs to treat patients");
    public static final TechEthicsModel TEthics2  =  new TechEthicsModel("Should we abandon privacy online?",22, R.drawable.techthics_2,20, 15, 1, TechEthicsAnalysis2, "Yes", "No", "No, allow law enforcement to collect and use information for investigating crimes or wrongdoers", "No, allow if user has granted permissions");
    public static final TechEthicsModel TEthics3  =  new TechEthicsModel("Should we give robots the right to kill?",22, R.drawable.techthics_3,20, 15, 1, TechEthicsAnalysis3, "Yes", "No", "Yes, as far as chemical and biological warfare is not used", "No, robots are not smart enough to differentiate civilians or targets");
    public static final TechEthicsModel TEthics4  =  new TechEthicsModel("Should biological weapons be allowed to build whose deliberate release by attackers could cause one or more of a variety of different diseases?",20, R.drawable.techthics_4,20, 15, 0, TechEthicsAnalysis4, "Yes", "No", "Yes, as far as it is for research purpose", "No, it is dangerous as nuclear");
    public static final TechEthicsModel TEthics5  =  new TechEthicsModel("Should technology be allowed to decode the human genome?",22, R.drawable.techthics_5,20, 15, 2, TechEthicsAnalysis5, "Yes", "No", "Yes, as it would lead to creating personalized medicine", "No, as insurers and prospective employers may use a person’s future health information");
    public static final TechEthicsModel TEthics6  =  new TechEthicsModel("Should data chip implants be allowed in children or people?",22, R.drawable.techthics_6,20, 15, 1, TechEthicsAnalysis6, "Yes", "No", "Yes, as paramedics and doctors get access to the medical records", "No, as personal life be compromised by insurers, prospective employers and law enforcement");
    public static final TechEthicsModel TEthics7  =  new TechEthicsModel("Should interspecies research allowed for experiments involving animal embryos and human stem?",20, R.drawable.techthics_7,20, 15, 1, TechEthicsAnalysis7, "Yes", "No", "Yes, to grow human organs in animals", "No, religious reasons and non-veg may turn into cannibalism");
    public static final TechEthicsModel TEthics8  =  new TechEthicsModel("Should creators of deepfake tools – FakeApp, Faceswap, and DeepFaceLab held responsible for harms caused and are likely to cause to innocent people?",20, R.drawable.techthics_8,20, 15, 1, TechEthicsAnalysis8, "Yes", "No", "No, but governing body applied to provide fake score", "No, it is similar to fake news");
    public static final TechEthicsModel TEthics9  =  new TechEthicsModel("Should U.S. government be allowed to experiment the virus-carrying insects to help crops fight threats such as pests, drought, or pollution?",20, R.drawable.techthics_9,20, 15, 2, TechEthicsAnalysis9, "Yes", "No", "Yes, as it will prevent crop failure driven by climate change", "No, as it could be turned into bio-weapons");
    public static final TechEthicsModel TEthics10 =  new TechEthicsModel("Should smart devices be stopped from tracking you or sharing data with third-party companies?",20, R.drawable.techthics_10,20, 15, 1, TechEthicsAnalysis10, "Yes", "No, as far as sensitive data is not shared", "Yes, smart devices should stop tracking all data", "No, but companies should provide reports in terms of the data shared");
    public static final TechEthicsModel TEthics11 =  new TechEthicsModel("Should pharmaceutical companies be allowed to use physician's data to recruit them for studies on new drugs or devices?",20, R.drawable.techthics_11,20, 15, 0, TechEthicsAnalysis11, "Yes", "No", "Yes, as it will drive to focussed research", "No, as it is conflict of interest when researchers get paid by companies");
    public static final TechEthicsModel TEthics12 =  new TechEthicsModel("Should human society move towards social credit system on points based on our behaviors?",20, R.drawable.techthics_12,20, 15, 1, TechEthicsAnalysis12, "Yes", "No", "Yes, as good behaviors can help build better community", "No, our human society has grown through challenging the norms");
    public static final TechEthicsModel TEthics13 =  new TechEthicsModel("Should criminal sentencing software be used to determine the criminal and/or determine the length and severity of sentence?",20, R.drawable.techthics_13,20, 15, 3, TechEthicsAnalysis13, "Yes", "No", "Yes, as past records on crimes can help increase severity", "No, as human biases on race, social status are part of software");
    public static final TechEthicsModel TEthics14 =  new TechEthicsModel("Should police officers be given ability to access driver’s phone after a crash to see if they were using the device in the time leading to the event?",20, R.drawable.techthics_14,20, 15, 0, TechEthicsAnalysis14, "Yes", "No", "Yes, as fear may prevent people from abusing the law", "No, as human privacy and personal data will be violated");
    public static final TechEthicsModel TEthics15 =  new TechEthicsModel("Should emotion recognition software be incorporated to allow companies to see exactly how you respond and react during shopping, eating or playing video?",20, R.drawable.techthics_15,20, 15, 3, TechEthicsAnalysis15, "Yes", "No", "Yes, as it will lead to custom software", "No, as companies will manipulate games to affect behaviors");
    public static final TechEthicsModel TEthics16 =  new TechEthicsModel("Should companies pay to Ransomware who seize control of your computer or device and lock you out, threatening to steal or delete important files?",20, R.drawable.techthics_16,20, 15, 3, TechEthicsAnalysis16, "Yes", "No", "Yes, as the loss is damaging to company and its customers", "No, as it encourages Ransonware to make it a business");
    public static final TechEthicsModel TEthics17 =  new TechEthicsModel("Should cell phone companies like Apple take requests from law enforcement agencies to handover customer data for access to devices?",20, R.drawable.techthics_17,20, 15, 1, TechEthicsAnalysis17, "Yes", "No", "Yes, as it can help catch criminals", "No, as it violates human privacy");
    public static final TechEthicsModel TEthics18 =  new TechEthicsModel("Should Citizen mobile app be allowed to stream live crimes and incidents?",20, R.drawable.techthics_18,20, 15, 1, TechEthicsAnalysis18, "Yes", "No", "Yes, as it can provide support when police is unable to reach quickly", "No, live crime events should be handled by police department");
    public static final TechEthicsModel TEthics19 =  new TechEthicsModel("Should \"Woebot\" an AI powered mobile app be used as mental therapist?",20, R.drawable.techthics_19,20, 15, 3, TechEthicsAnalysis19, "Yes", "No", "Yes, Psychologists are known to provide placebo effect to patients", "No, as anxiety and depression may lead to death of person");
    public static final TechEthicsModel TEthics20 =  new TechEthicsModel("Should Programmers need ethics similar to Hippocratic oath when designing the technologies that influence people’s lives?",20, R.drawable.techthics_20,20, 15, 2, TechEthicsAnalysis20, "Yes", "No", "Yes, as computer professionals are on the front lines of software decisions", "No, as decisions are made by businesses not professionals");
    public static final TechEthicsModel TEthics21 =  new TechEthicsModel("Should Facebook, Twitter and WhatsApp control political advertising or message forwarding during elections?",20, R.drawable.techthics_21,20, 15, 2, TechEthicsAnalysis21, "Yes", "No", "Yes, as messages influence political self-expression, and real-world voting behaviour of millions of people", "No, as it is part of freedom of speech");
    public static final TechEthicsModel TEthics22 =  new TechEthicsModel("Should Robo advisors be used to provide financial advise to investors?",20, R.drawable.techthics_22,18, 15, 1, TechEthicsAnalysis22, "Yes", "No", "Yes, as AI machines can provide cost effective solution and reach to many customers at lower price point", "No, as human investments are complex and are a function of current and future needs");
    public static final TechEthicsModel TEthics23 =  new TechEthicsModel("Should Facebook and other companies be allowed to share online user data (like Facebook profiles, likes, friends)?",20, R.drawable.techthics_23,20, 15, 0, TechEthicsAnalysis23, "Yes", "No", "Yes, as free service means companies can use user data as source of revenue", "No, as it violates privacy by using data to do behavioural micro-targeting");
    public static final TechEthicsModel TEthics24 =  new TechEthicsModel("Should we strive to integrate AI into society if it means many people will lose their jobs — and quite possibly their livelihood?",20, R.drawable.techthics_24,20, 15, 0, TechEthicsAnalysis24, "Yes, we can migrate the humans to advanced skills", "No", "Yes, as humans will evolve to move out of those tasks", "No, it will create wealth inequality and civil unrest");
    public static final TechEthicsModel TEthics25 =  new TechEthicsModel("Should we stop building AI, as it can go rogue, and create unintended consequences from its actions and create harmful goals?",20, R.drawable.techthics_25,20, 15, 1, TechEthicsAnalysis25, "Yes", "No", "Yes, humans need to create ethical and moral bots", "No, AI technology is not yet capable of achieving the dangerous feat of self-awareness");
    public static final TechEthicsModel TEthics26 =  new TechEthicsModel("Should robots be granted human rights or citizenship?",20, R.drawable.techthics_26,20, 15, 1, TechEthicsAnalysis26, "Yes", "No", "Yes, as human society will start accepting robots and build roboethics", "No, robots have not reached the level of self-awareness");

    public static final TechEthicsModel TechEthicsDataList[];

    static {
        TechEthicsDataList = new TechEthicsModel[]{
                TEthics1,  TEthics2,  TEthics3,  TEthics4,  TEthics5,
                TEthics6,  TEthics7,  TEthics8,  TEthics9,  TEthics10,
                TEthics11, TEthics12, TEthics13, TEthics14, TEthics15,
                TEthics16, TEthics17, TEthics18, TEthics19, TEthics20,
                TEthics21, TEthics22, TEthics23, TEthics24, TEthics25,
                TEthics26
        };
    }
}
