//  TechEthicsData.java
//  MoralIQ
//
//  Created by Simone Karani on 2/9/20.
//  Copyright © 2020 MoralIQ. All rights reserved.
//

package com.simonekarani.moraliq.techethics;

import com.simonekarani.moraliq.R;

public class TechEthicsData {
    public static final String TechEthicsAnalysis1   = "Re-gifting is the process of getting a gift, and then giving that gift to someone else. It's generally frowned upon because it shows that you didn't really appreciate that gift and you don't care about the person who gave it to you.";
    public static final String TechEthicsAnalysis2   = "Re-gifting is the process of getting a gift, and then giving that gift to someone else. It's generally frowned upon because it shows that you didn't really appreciate that gift and you don't care about the person who gave it to you.";
    public static final String TechEthicsAnalysis3   = "Re-gifting is the process of getting a gift, and then giving that gift to someone else. It's generally frowned upon because it shows that you didn't really appreciate that gift and you don't care about the person who gave it to you.";
    public static final String TechEthicsAnalysis4   = "Re-gifting is the process of getting a gift, and then giving that gift to someone else. It's generally frowned upon because it shows that you didn't really appreciate that gift and you don't care about the person who gave it to you.";
    public static final String TechEthicsAnalysis5   = "Re-gifting is the process of getting a gift, and then giving that gift to someone else. It's generally frowned upon because it shows that you didn't really appreciate that gift and you don't care about the person who gave it to you.";
    public static final String TechEthicsAnalysis6   = "Re-gifting is the process of getting a gift, and then giving that gift to someone else. It's generally frowned upon because it shows that you didn't really appreciate that gift and you don't care about the person who gave it to you.";
    public static final String TechEthicsAnalysis7   = "Re-gifting is the process of getting a gift, and then giving that gift to someone else. It's generally frowned upon because it shows that you didn't really appreciate that gift and you don't care about the person who gave it to you.";
    public static final String TechEthicsAnalysis8   = "Re-gifting is the process of getting a gift, and then giving that gift to someone else. It's generally frowned upon because it shows that you didn't really appreciate that gift and you don't care about the person who gave it to you.";
    public static final String TechEthicsAnalysis9   = "Re-gifting is the process of getting a gift, and then giving that gift to someone else. It's generally frowned upon because it shows that you didn't really appreciate that gift and you don't care about the person who gave it to you.";
    public static final String TechEthicsAnalysis10  = "Re-gifting is the process of getting a gift, and then giving that gift to someone else. It's generally frowned upon because it shows that you didn't really appreciate that gift and you don't care about the person who gave it to you.";
    public static final String TechEthicsAnalysis11  = "Re-gifting is the process of getting a gift, and then giving that gift to someone else. It's generally frowned upon because it shows that you didn't really appreciate that gift and you don't care about the person who gave it to you.";
    public static final String TechEthicsAnalysis12  = "Re-gifting is the process of getting a gift, and then giving that gift to someone else. It's generally frowned upon because it shows that you didn't really appreciate that gift and you don't care about the person who gave it to you.";
    public static final String TechEthicsAnalysis13  = "Re-gifting is the process of getting a gift, and then giving that gift to someone else. It's generally frowned upon because it shows that you didn't really appreciate that gift and you don't care about the person who gave it to you.";
    public static final String TechEthicsAnalysis14  = "Re-gifting is the process of getting a gift, and then giving that gift to someone else. It's generally frowned upon because it shows that you didn't really appreciate that gift and you don't care about the person who gave it to you.";
    public static final String TechEthicsAnalysis15  = "Re-gifting is the process of getting a gift, and then giving that gift to someone else. It's generally frowned upon because it shows that you didn't really appreciate that gift and you don't care about the person who gave it to you.";
    public static final String TechEthicsAnalysis16  = "Re-gifting is the process of getting a gift, and then giving that gift to someone else. It's generally frowned upon because it shows that you didn't really appreciate that gift and you don't care about the person who gave it to you.";
    public static final String TechEthicsAnalysis17  = "Re-gifting is the process of getting a gift, and then giving that gift to someone else. It's generally frowned upon because it shows that you didn't really appreciate that gift and you don't care about the person who gave it to you.";
    public static final String TechEthicsAnalysis18  = "Re-gifting is the process of getting a gift, and then giving that gift to someone else. It's generally frowned upon because it shows that you didn't really appreciate that gift and you don't care about the person who gave it to you.";
    public static final String TechEthicsAnalysis19  = "Re-gifting is the process of getting a gift, and then giving that gift to someone else. It's generally frowned upon because it shows that you didn't really appreciate that gift and you don't care about the person who gave it to you.";
    public static final String TechEthicsAnalysis20  = "Re-gifting is the process of getting a gift, and then giving that gift to someone else. It's generally frowned upon because it shows that you didn't really appreciate that gift and you don't care about the person who gave it to you.";
    public static final String TechEthicsAnalysis21  = "Re-gifting is the process of getting a gift, and then giving that gift to someone else. It's generally frowned upon because it shows that you didn't really appreciate that gift and you don't care about the person who gave it to you.";
    public static final String TechEthicsAnalysis22  = "Re-gifting is the process of getting a gift, and then giving that gift to someone else. It's generally frowned upon because it shows that you didn't really appreciate that gift and you don't care about the person who gave it to you.";
    public static final String TechEthicsAnalysis23  = "Re-gifting is the process of getting a gift, and then giving that gift to someone else. It's generally frowned upon because it shows that you didn't really appreciate that gift and you don't care about the person who gave it to you.";
    public static final String TechEthicsAnalysis24  = "Re-gifting is the process of getting a gift, and then giving that gift to someone else. It's generally frowned upon because it shows that you didn't really appreciate that gift and you don't care about the person who gave it to you.";
    public static final String TechEthicsAnalysis25  = "Re-gifting is the process of getting a gift, and then giving that gift to someone else. It's generally frowned upon because it shows that you didn't really appreciate that gift and you don't care about the person who gave it to you.";
    public static final String TechEthicsAnalysis26  = "Re-gifting is the process of getting a gift, and then giving that gift to someone else. It's generally frowned upon because it shows that you didn't really appreciate that gift and you don't care about the person who gave it to you.";

    public static final TechEthicsModel TEthics1  =  new TechEthicsModel("Should we edit our children's genes?",22, R.drawable.techthics_1,20, 30, 1, TechEthicsAnalysis1, "Yes", "No", "Maybe, to eliminate genetic related diseases", "Yes, to support generation of tissues and whole organs to treat patients");
    public static final TechEthicsModel TEthics2  =  new TechEthicsModel("Should we abandon privacy online?",22, R.drawable.techthics_2,20, 30, 1, TechEthicsAnalysis2, "Yes", "No", "No, allow law enforcement to collect and use information for investigating crimes or wrongdoers", "No, allow if user has granted permissions");
    public static final TechEthicsModel TEthics3  =  new TechEthicsModel("Should we give robots the right to kill?",22, R.drawable.techthics_3,20, 30, 1, TechEthicsAnalysis3, "Yes", "No", "Yes, as far as chemical and biological warfare is not used", "No, robots are not smart enough to differentiate civilians or targets");
    public static final TechEthicsModel TEthics4  =  new TechEthicsModel("Should biological weapons be allowed to build whose deliberate release by attackers could cause one or more of a variety of different diseases?",20, R.drawable.techthics_4,20, 30, 1, TechEthicsAnalysis4, "Yes", "No", "Yes, as far as it is for research purpose", "No, it is dangerous as nuclear");
    public static final TechEthicsModel TEthics5  =  new TechEthicsModel("Should technology be allowed to decode the human genome?",22, R.drawable.techthics_5,20, 30, 1, TechEthicsAnalysis5, "Yes", "No", "Yes, as it would lead to creating personalized medicine", "No, as insurers and prospective employers may use a person’s future health information");
    public static final TechEthicsModel TEthics6  =  new TechEthicsModel("Should data chip implants be allowed in children or people?",22, R.drawable.techthics_6,20, 30, 1, TechEthicsAnalysis6, "Yes", "No", "Yes, as paramedics and doctors get access to the medical records", "No, as personal life be compromised by insurers, prospective employers and law enforcement");
    public static final TechEthicsModel TEthics7  =  new TechEthicsModel("Should interspecies research allowed for experiments involving animal embryos and human stem?",20, R.drawable.techthics_7,20, 30, 1, TechEthicsAnalysis7, "Yes", "No", "Yes, to grow human organs in animals", "No, religious reasons and non-veg may turn into cannibalism");
    public static final TechEthicsModel TEthics8  =  new TechEthicsModel("Should the creators of the deepfake tools – FakeApp, Faceswap, and DeepFaceLab – held responsible for harms caused / and are likely to cause to innocent people?",20, R.drawable.techthics_8,20, 30, 1, TechEthicsAnalysis8, "Yes", "No", "No, but governing body applied to provide fake score", "No, it is similar to fake news");
    public static final TechEthicsModel TEthics9  =  new TechEthicsModel("Should U.S. government be allowed to experiment the virus-carrying insects to help crops fight threats such as pests, drought, or pollution?",20, R.drawable.techthics_9,20, 30, 1, TechEthicsAnalysis9, "Yes", "No", "Yes, as it will prevent crop failure driven by climate change", "No, as it could be turned into bio-weapons");
    public static final TechEthicsModel TEthics10 =  new TechEthicsModel("Should smart devices be stopped from tracking you or sharing data with third-party companies?",20, R.drawable.techthics_10,20, 30, 1, TechEthicsAnalysis10, "Yes", "No, as far as sensitive data is not shared", "Yes, smart devices should stop tracking all data", "No, but companies should provide reports in terms of the data shared");
    public static final TechEthicsModel TEthics11 =  new TechEthicsModel("Should pharmaceutical companies be allowed to use physician's data to recruit them for studies on new drugs or devices?",20, R.drawable.techthics_11,20, 30, 1, TechEthicsAnalysis11, "Yes", "No", "Yes, as it will drive to focussed research", "No, as it is conflict of interest when researchers get paid by companies");
    public static final TechEthicsModel TEthics12 =  new TechEthicsModel("Should human society move towards social credit system on points based on our behaviors?",20, R.drawable.techthics_12,20, 30, 1, TechEthicsAnalysis12, "Yes", "No", "Yes, as good behaviors can help build better community", "No, our human society has grown through challenging the norms");
    public static final TechEthicsModel TEthics13 =  new TechEthicsModel("Should criminal sentencing software be used to determine the criminal and/or determine the length and severity of sentence?",20, R.drawable.techthics_13,20, 30, 1, TechEthicsAnalysis13, "Yes", "No", "Yes, as past records on crimes can help increase severity", "No, as human biases on race, social status are part of software");
    public static final TechEthicsModel TEthics14 =  new TechEthicsModel("Should police officers be given the ability to access driver’s phone after a crash to see if they were using the device in the time leading up to the event?",20, R.drawable.techthics_14,20, 30, 1, TechEthicsAnalysis14, "Yes", "No", "Yes, as fear may prevent people from abusing the law", "No, as human privacy and personal data will be violated");
    public static final TechEthicsModel TEthics15 =  new TechEthicsModel("Should emotion recognition software be incorporated to allow companies to see exactly how you respond and react during shopping, eating or playing video?",20, R.drawable.techthics_15,20, 30, 1, TechEthicsAnalysis15, "Yes", "No", "Yes, as it will lead to custom software", "No, as companies will manipulate games to affect behaviors");
    public static final TechEthicsModel TEthics16 =  new TechEthicsModel("Should companies pay to Ransomware who seize control of your computer or device and lock you out, threatening to steal or delete important files?",20, R.drawable.techthics_16,20, 30, 1, TechEthicsAnalysis16, "Yes", "No", "Yes, as the loss is damaging to company and its customers", "No, as it encourages Ransonware to make it a business");
    public static final TechEthicsModel TEthics17 =  new TechEthicsModel("Should cell phone companies like Apple take requests from law enforcement agencies to handover customer data for access to devices?",20, R.drawable.techthics_17,20, 30, 1, TechEthicsAnalysis26, "Yes", "No", "Yes, as it can help catch criminals", "No, as it violates human privacy");
    public static final TechEthicsModel TEthics18 =  new TechEthicsModel("Should Citizen mobile app be allowed to stream live crimes and incidents?",20, R.drawable.techthics_18,20, 30, 1, TechEthicsAnalysis18, "Yes", "No", "Yes, as it can provide support when police is unable to reach quickly", "No, live crime events should be handled by police department");
    public static final TechEthicsModel TEthics19 =  new TechEthicsModel("Should \"Woebot\" an AI powered mobile app be used as mental therapist?",20, R.drawable.techthics_19,20, 30, 1, TechEthicsAnalysis19, "Yes", "No", "Yes, Psychologists are known to provide placebo effect to patients", "No, as anxiety and depression may lead to death of person");
    public static final TechEthicsModel TEthics20 =  new TechEthicsModel("Should Programmers need ethics similar to Hippocratic oath when designing the technologies that influence people’s lives?",20, R.drawable.techthics_20,20, 30, 1, TechEthicsAnalysis20, "Yes", "No", "Yes, as computer professionals are on the front lines of software decisions", "No, as decisions are made by businesses not professionals");
    public static final TechEthicsModel TEthics21 =  new TechEthicsModel("Should Facebook, Twitter and WhatsApp control political advertising or message forwarding during elections?",20, R.drawable.techthics_21,20, 30, 1, TechEthicsAnalysis21, "Yes", "No", "Yes, as messages influence political self-expression, and real-world voting behaviour of millions of people", "No, as it is part of freedom of speech");
    public static final TechEthicsModel TEthics22 =  new TechEthicsModel("Should Robo advisors be used to provide financial advise to investors?",20, R.drawable.techthics_22,20, 30, 1, TechEthicsAnalysis22, "Yes", "No", "Yes, as AI machines can provide cost effective solution and reach to many customers at lower price point", "No, as human investments are complex and are a function of current and future needs");
    public static final TechEthicsModel TEthics23 =  new TechEthicsModel("Should Facebook and other companies be allowed to share online user data (like Facebook profiles, likes, friends)?",20, R.drawable.techthics_23,20, 30, 1, TechEthicsAnalysis23, "Yes", "No", "Yes, as free service means companies can use user data as source of revenue", "No, as it violates privacy by using data to do behavioural micro-targeting");
    public static final TechEthicsModel TEthics24 =  new TechEthicsModel("Should we strive to integrate AI into society if it means many people will lose their jobs — and quite possibly their livelihood?",20, R.drawable.techthics_24,20, 30, 1, TechEthicsAnalysis24, "Yes, we can migrate the humans to advanced skills", "No", "Yes, as humans will evolve to move out of those tasks", "No, it will create wealth inequality and civil unrest");
    public static final TechEthicsModel TEthics25 =  new TechEthicsModel("Should we stop building AI, as it can go rogue, and create unintended consequences from its actions and create harmful goals?",20, R.drawable.techthics_25,20, 30, 1, TechEthicsAnalysis25, "Yes", "No, as that is science fiction", "Yes, humans need to create ethical and moral bots", "No, AI technology is not yet capable of achieving the dangerous feat of self-awareness");
    public static final TechEthicsModel TEthics26 =  new TechEthicsModel("Should robots be granted human rights or citizenship?",20, R.drawable.techthics_26,20, 30, 1, TechEthicsAnalysis26, "Yes", "No", "Yes, as human society will start accepting robots and build roboethics", "No, robots have not reached the level of self-awareness");

    public static final TechEthicsModel TechEthicsDataList[];

    static {
        TechEthicsDataList = new TechEthicsModel[]{
                TEthics1,  TEthics2,  TEthics3,  TEthics4,  TEthics5,
                TEthics6,  TEthics7,  TEthics8,  TEthics9,  TEthics10,
                TEthics11, TEthics12, TEthics13, TEthics14, TEthics15,
                TEthics16, TEthics17, TEthics18, TEthics19, TEthics20,
                TEthics21, TEthics22, TEthics23, TEthics24, TEthics25,
                TEthics26
        };
    }
}
