//
//  BusinessEthicsData.java
//  MoralIQ
//
//  Created by Simone Karani on 2/9/20.
//  Copyright © 2020 MoralIQ. All rights reserved.
//

package com.simonekarani.moraliq.bizethics;

import com.simonekarani.moraliq.R;
import com.simonekarani.moraliq.bizethics.BusinessEthicsModel;

public class BusinessEthicsData {
    public static final BusinessEthicsModel BEthics1   =  new BusinessEthicsModel("Is it ethical for companies to fire or otherwise punish employees for what they post about?",20, R.drawable.bizthics_1,20, 30, "Yes", "No, if identity of company is not mentioned", "Yes, if social terms of conduct was signed", "No, it violates free speech");
    public static final BusinessEthicsModel BEthics2   =  new BusinessEthicsModel("Should an employer be allowed to fire for staying home - family responsibilities and caregiving, including pregnancy and eldercare?",20, R.drawable.bizthics_2,20, 30, "Yes", "No", "Yes, as business work responsibilities do not change", "No, EEOC states to avoid family related discrimination");
    public static final BusinessEthicsModel BEthics3   =  new BusinessEthicsModel("Should cosmetic company be held responsible for health conditions caused by chemicals in their products - linked to breast cancer, or others?",20, R.drawable.bizthics_3,20, 30, "Yes", "No, but it should trigger study by FDA", "Yes, if any chemical in the product has any toxic implication", "No, difficult to associate a link need data");
    public static final BusinessEthicsModel BEthics4   =  new BusinessEthicsModel("Should scientists torture animals for lab trials or experiments for medical purposes or cosmetics?",20, R.drawable.bizthics_4,20, 30, "Yes", "No, they should come up with other forms of testing", "Yes, there is no better alternative to testing", "No, as human biological system is different than animals");
    public static final BusinessEthicsModel BEthics5   =  new BusinessEthicsModel("Should scientists torture animals for lab trials or experiments for cosmetics?",20, R.drawable.bizthics_5,20, 30, "Yes", "No, testing results have failed", "Yes, there is no better alternative to testing", "No, as human skin composition is different than animals");
    public static final BusinessEthicsModel BEthics6   =  new BusinessEthicsModel("Should businesses be held responsible for deliberately dumping waste - radioactive, nuclear, and others and destroying occean life?",20, R.drawable.bizthics_6,20, 30, "Yes", "No", "Yes, business responsible for solutions on waste", "No, there is no better place to dump");
    public static final BusinessEthicsModel BEthics7   =  new BusinessEthicsModel("Should businesses be held responsible for creating plastic waste of occean and destroying marine life?",20, R.drawable.bizthics_7,20, 30, "Yes, plastic wrapping by created for products", "No", "Yes, decomposable wrappings should be created", "No, as humans are dumping plastic in occean");
    public static final BusinessEthicsModel BEthics8   =  new BusinessEthicsModel("Should Companies be legally allowed to monitor your company email and internet browser history?",20, R.drawable.bizthics_8,20, 30, "Yes", "No, as it violates privacy", "Yes, as work laptop is provided by company", "No, there are certain boundaries even though they are provided by company");
    public static final BusinessEthicsModel BEthics9   =  new BusinessEthicsModel("Should Companies be responsible for un-safe handling of bio-hazards in labs or workplace?",20, R.drawable.bizthics_9,20, 30, "Yes, safe environment is company responsibility", "No", "Yes, but can't be held responsible for human negligence", "No, every worker is responsible for his/her own safety");
    public static final BusinessEthicsModel BEthics10  =  new BusinessEthicsModel("Should Companies be responsible for employee non-compliance for EEO and racial discrimination at workplace?",20, R.drawable.bizthics_10,20, 30, "Yes", "No", "Yes, policy enforcement is company responsibility", "No, company cannot track every employee actions");
    public static final BusinessEthicsModel BEthics11  =  new BusinessEthicsModel("Should drug or pharmaceutical companies be responsible for data integrity of clinical trials?",20, R.drawable.bizthics_11,20, 30, "Yes", "No", "Yes, as they are experts and have all trial data", "No, FDA is responsible for inspection");
    public static final BusinessEthicsModel BEthics12  =  new BusinessEthicsModel("Should monopoly company have the right to exploit the consumers based on the demand of the market?",20, R.drawable.bizthics_12,20, 30, "Yes, they earned it", "No, consumer rights have been designed to guard monopoly", "Yes, as there is no absolute monopoly", "No, as lowering the price beyond margins can destroy competitors");
    public static final BusinessEthicsModel BEthics13  =  new BusinessEthicsModel("Should busineesses report the use of child labour involved for the manufacturing of their product?",20, R.drawable.bizthics_13,20, 30, "Yes, against UN policy of child labor", "No", "Yes, child labor has to be discouraged", "No, consumers should care of ingredients");
    public static final BusinessEthicsModel BEthics14  =  new BusinessEthicsModel("Should consumers boycott products from companies who have been accussed of falsifying environmental data?",20, R.drawable.bizthics_14,20, 30, "Yes, any abuse should not be tolerated for profit reasons", "No, products should exist on their merits in marketplace", "Yes, companies should be punished", "No, as every business abuses environment");
    public static final BusinessEthicsModel BEthics15  =  new BusinessEthicsModel("Should busineesses be allowed to provide incentives or kickbacks to win businesses as is done in some parts of the world?",20, R.drawable.bizthics_15,20, 30, "Yes, if permitted by laws of country", "No, companies should follow business ethics", "Yes, if allowed by company laws", "No, scandal affects name and reputation worldwide");
    public static final BusinessEthicsModel BEthics16  =  new BusinessEthicsModel("Should busineesses be allowed deceptive advertising to get consumers into buying their products?",20, R.drawable.bizthics_16,20, 30, "Yes, as far as it is not scamming", "No, the product will lose future credibility", "Yes, as far as it represents the product ingredients", "No, as consumer protection can file case for malpractices");
    public static final BusinessEthicsModel BEthics17  =  new BusinessEthicsModel("Should the busineesses be allowed to create devices to show low emissions in order to beat competitions?",20, R.drawable.bizthics_17,20, 30, "Yes, if there is no human danger", "No, the product should show what are factual data", "Yes, as far as the actual data meets the standards", "No, malpractice is federal crime");
    public static final BusinessEthicsModel BEthics18  =  new BusinessEthicsModel("Should the ministers/Presidents/Prime ministers of the country allowed to hold businesses or be board member in businesses?",20, R.drawable.bizthics_18,20, 30, "Yes, if he is not involved in day today operations", "No, conflict arises", "Yes, if he is not involved with business operations", "No, businesses can win contracts in the person's name");
    public static final BusinessEthicsModel BEthics19  =  new BusinessEthicsModel("Should pharmaceuticals be allowed to use drug patents to prevent generics from building similar products?",20, R.drawable.bizthics_19,20, 30, "Yes, as far as they don't abuse drug pricing", "No, generic drugs for mass market cannot be patented", "Yes, or there won't be any R&D investments from pharmaceuticals", "No, they may abuse pricing on drugs");
    public static final BusinessEthicsModel BEthics20  =  new BusinessEthicsModel("Should products from country be boycotted for border clashes or trade war?",20, R.drawable.bizthics_20,20, 30, "Yes, it sends strong message to partner country", "No, as every international company has national presence so it affects both countries", "Yes, if national threat is detected", "No, politics should not be combined with businesses");
    public static final BusinessEthicsModel BEthics21  =  new BusinessEthicsModel("Should travel businesses inform customers of socio-economic-political concerns to travelers?",20, R.drawable.bizthics_21,20, 30, "Yes", "No, as it is travelers responsibility", "Yes, as most travelers have only looked at travel sites", "No, only risk related topics can be mentioned");
    public static final BusinessEthicsModel BEthics22  =  new BusinessEthicsModel("Should reward system in financial/insurance industry be related to selling applications or claims?",20, R.drawable.bizthics_22,20, 30, "Yes, as the sell of applications/claims helps grow revenues", "No, as agents sell wrong information to clients", "Yes, similar to sales agent", "No, in long term agents/businesses lose credibility");
    public static final BusinessEthicsModel BEthics23  =  new BusinessEthicsModel("Should products/businesses be punished for supporting social issues - LGBT, anti-ICE?",20, R.drawable.bizthics_23,20, 30, "Yes, as business policy should be fair and supporting their consumers", "No, CEO donations or support should not be considered as company support", "Yes, as businesses may force support from employees", "No, as company support is not related to product/service");
    public static final BusinessEthicsModel BEthics24  =  new BusinessEthicsModel("Should real estate agent be allowed to refer mortgage broker to borrowers?",20, R.drawable.bizthics_24,20, 30, "Yes, referrals are not forceful", "No, as conflict of amount approval can arise", "Yes, as they can help save time for buyers", "No, as they get paid for referral");
    public static final BusinessEthicsModel BEthics25  =  new BusinessEthicsModel("Should consumers ban movies which have been made to support the growth of family member - nepotism?",20, R.drawable.bizthics_25,20, 30, "Yes", "No, nepotism is a part of every business", "Yes, nepotism should be banned", "No, true merits of the movie will make it successful");

    public static final BusinessEthicsModel BizEthicsDataList[];

    static {
        BizEthicsDataList = new BusinessEthicsModel[]{
                BEthics1,  BEthics2,  BEthics3,  BEthics4,  BEthics5,
                BEthics6,  BEthics7,  BEthics8,  BEthics9,  BEthics10,
                BEthics11, BEthics12, BEthics13, BEthics14, BEthics15,
                BEthics16, BEthics17, BEthics18, BEthics19, BEthics20,
                BEthics21, BEthics22, BEthics23, BEthics24, BEthics25
        };
    }
}
